/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nms.rest.server.apis;


import com.nms.rest.server.models.Charge;
import com.nms.rest.server.models.ChargeDto;
import com.nms.rest.server.models.ResponseModel;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-30T11:45:01.773Z[GMT]")
public interface ChargesApi {

    @Operation(summary = "add a new Charge", description = "Adds add a new Charge to the system", tags={ "Charges Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Charge created"),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
        
        @ApiResponse(responseCode = "409", description = "An existing Charge already exists") })
    @RequestMapping(value = "/charges",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Charge> addCharge(@Parameter(in = ParameterIn.DEFAULT, description = "Charge to add", schema=@Schema()) @Valid @RequestBody ChargeDto body);


    @Operation(summary = "Delete a Charge", description = "Delete Charge", tags={ "Charges Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Deleted."),
        
        @ApiResponse(responseCode = "400", description = "Unable to delete service.") })
    @RequestMapping(value = "/charges/{chargeId}",
        method = RequestMethod.DELETE)
    ResponseEntity<ResponseModel> deleteChargeById(@Parameter(in = ParameterIn.PATH, description = "The Charge Id.", required=true, schema=@Schema()) @PathVariable("chargeId") Long chargeId);


    @Operation(summary = "searches for Charge by name", description = "", tags={ "Charges Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "search results matching criteria", content = @Content(schema = @Schema(implementation = Charge.class))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/charges/{chargeName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Charge> getChargeByName(@Parameter(in = ParameterIn.PATH, description = "The ChargesName used to update the service information", required=true, schema=@Schema()) @PathVariable("chargeName") String chargeName);


    @Operation(summary = "get all Charges", description = "", tags={ "Charges Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Get all Charges from database", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Charge.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/charges",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Charge>> getCharges();


    @Operation(summary = "update Charge", description = "Update Charge", tags={ "Charges Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Charge updated.", content = @Content(schema = @Schema(implementation = Charge.class))),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid") })
    @RequestMapping(value = "/charges/{chargeId}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Charge> updateChargeById(@Parameter(in = ParameterIn.PATH, description = "The ChargeId used to update the service information", required=true, schema=@Schema()) @PathVariable("chargeId") Long chargeId, @Parameter(in = ParameterIn.DEFAULT, description = "The Charges to update.", required=true, schema=@Schema()) @Valid @RequestBody ChargeDto body);

}

