/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nms.rest.server.apis;


import com.nms.rest.server.models.Invoice;
import com.nms.rest.server.models.InvoiceDto;
import com.nms.rest.server.models.ResponseModel;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-12-06T11:07:16.529Z[GMT]")
public interface InvoiceApi {

    @Operation(summary = "add a new Invoice", description = "Adds add a new Invoice to the system", tags={ "Invoice Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Application created"),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
        
        @ApiResponse(responseCode = "409", description = "an existing Application already exists") })
    @RequestMapping(value = "/invoice",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseModel> addInvoice(@Parameter(in = ParameterIn.DEFAULT, description = "Application to add", schema=@Schema()) @Valid @RequestBody InvoiceDto body);


    @Operation(summary = "Delete a Application", description = "Delete Application", tags={ "Invoice Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Deleted."),
        
        @ApiResponse(responseCode = "400", description = "Unable to delete service.") })
    @RequestMapping(value = "/invoice/{invoiceId}",
        method = RequestMethod.DELETE)
    ResponseEntity<ResponseModel> deleteInvoicenById(@Parameter(in = ParameterIn.PATH, description = "The Application Id.", required=true, schema=@Schema()) @PathVariable("invoiceId") Long invoiceId);


    @Operation(summary = "get all applications", description = "", tags={ "Invoice Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Get all Invoice from database", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Invoice.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/invoice",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Invoice>> getInvoice();


    @Operation(summary = "Get an Application", description = "Get Application", tags={ "Invoice Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Application retrieved.", content = @Content(schema = @Schema(implementation = Invoice.class))),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid") })
    @RequestMapping(value = "/invoice/{invoiceId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Invoice> getInvoiceById(@Parameter(in = ParameterIn.PATH, description = "The Application Id.", required=true, schema=@Schema()) @PathVariable("invoiceId") Long invoiceId);


    @Operation(summary = "update Invoice", description = "Update Invoice", tags={ "Invoice Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Application updated.", content = @Content(schema = @Schema(implementation = Invoice.class))),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid") })
    @RequestMapping(value = "/invoice/{invoiceId}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Invoice> updateInvoiceById(@Parameter(in = ParameterIn.PATH, description = "The InvoiceId used to update the service information", required=true, schema=@Schema()) @PathVariable("invoiceId") Long invoiceId, @Parameter(in = ParameterIn.DEFAULT, description = "The Application to update.", required=true, schema=@Schema()) @Valid @RequestBody InvoiceDto body);

}

