server:
  port: 9009

spring:
  application:
    name: NUMBER-MANAGEMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  mail:
    host: smtp.gmail.com
    port: 465
    username: nmsystem85@gmail.com
    password: numberManagementSystem
    properties:
      "mail.smtp.starttls.enable": true
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.ssl.enable": true
      "debug": true


    #MySQL
  datasource:
   # url: jdbc:mysql://localhost:3306/nms?serverTimezone=UTC&createDatabaseIfNotExist=true
    url: jdbc:mysql://nms.cvhqs5nfkn0p.us-east-1.rds.amazonaws.com:3306/nms?serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
   # username: root
    password: password
  jpa:
    demographics-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    enabled: false

  jackson:
    serialization:
      fail-on-empty-beans: false
#      WRITE_DATES_AS_TIMESTAMPS: false
#    date-format: io.swagger.RFC3339DateFormat
token:
  expiration_time: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739
  activation:
    url:
      path: /users/activate/**:password
  reset:
    token:
      expiration_time: 360000
email:
  verification:
    token:
      expiration_time: 864000000
authorization:
  token:
    header:
      prefix: Bearer
      name: Authorization
login:
  url:
    path: /users/login

signup:
  url:
    path: /users/signup

jsp:
  url:
    path: /**

password:
  reset:
    request:
      path: /password-reset-request
    path: /password-reset

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.glassfish.jersey: ERROR
    org.reflections: ERROR
    com.hcb.services.biorouter: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springfox:
  documentation:
    open-api:
      v2:
        path: /api-docs


nms:
  server:
    url: http://apps.showcase.com.ng/api-server/identity/validate/?token=

  api:
    key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBsaWNhdGlvbklkIjoibnVtYmVyaW5nIiwiZXhwIjozNjg1MjgyNjIxLCJpYXQiOjE1Mzc3OTg5NzQsInVzZXJuYW1lIjoibnVtYmVyaW5nX2FkbWluIn0.EeMzWArhIMw0PnRjWX4oWlT985Id3DXHJS8mZzAqmz0
