/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nms.apis;


import com.nms.models.ApprovalStage;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-30T11:45:01.773Z[GMT]")
public interface ApprovalStageApi {

    @Operation(summary = "get all Stages", description = "", tags = {"Approval Stages Management"})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Get allApproval Stages from database", content = @Content(array = @ArraySchema(schema = @Schema(implementation = ApprovalStage.class)))),

            @ApiResponse(responseCode = "400", description = "bad input parameter")})
    @RequestMapping(value = "/approvalStage",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<ApprovalStage>> getapprovalStagees();
}

