/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nms.apis;


import com.nms.models.EmailDto;
import com.nms.models.ResponseModel;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-30T11:45:01.773Z[GMT]")
public interface EmailApi {


    @Operation(summary = "sends a new Email", description = "sends add a new Email to the system", tags = {"Email Management"})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Email sent"),

            @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),

            @ApiResponse(responseCode = "409", description = "an existing Email already exists")})
    @RequestMapping(value = "/email",
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<ResponseModel> sendEmail(@Parameter(in = ParameterIn.DEFAULT, description = "Email to add", schema = @Schema()) @Valid @RequestBody EmailDto body);
}

