/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nms.apis;

import com.nms.models.Fee;
import com.nms.models.FeeDto;
import com.nms.models.ResponseModel;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-30T11:45:01.773Z[GMT]")
public interface FeesApi {

    @Operation(summary = "add a new Fee", description = "Adds add a new Fee to the system", tags={ "Fee Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Fee created"),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
        
        @ApiResponse(responseCode = "409", description = "An existing Fee already exists") })
    @RequestMapping(value = "/fees",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Fee> addFee(@Parameter(in = ParameterIn.DEFAULT, description = "Fee to add", schema=@Schema()) @Valid @RequestBody FeeDto body);


    @Operation(summary = "Delete a Fee", description = "Delete Fee", tags={ "Fee Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Deleted."),
        
        @ApiResponse(responseCode = "400", description = "Unable to delete service.") })
    @RequestMapping(value = "/fees/{feeId}",
        method = RequestMethod.DELETE)
    ResponseEntity<ResponseModel> deleteFeeById(@Parameter(in = ParameterIn.PATH, description = "The Fee Id.", required=true, schema=@Schema()) @PathVariable("feeId") Long feeId);


    @Operation(summary = "searches for Fee by name", description = "", tags={ "Fee Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "search results matching criteria", content = @Content(schema = @Schema(implementation = Fee.class))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/fees/{feeName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Fee> getFeeByName(@Parameter(in = ParameterIn.PATH, description = "The FeeName used to update the service information", required=true, schema=@Schema()) @PathVariable("feeName") String feeName);


    @Operation(summary = "get all fees", description = "", tags={ "Fee Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Get all Fees from database", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Fee.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/fees",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Fee>> getFees();


    @Operation(summary = "update Fee", description = "Update Fee", tags={ "Fee Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Fee updated.", content = @Content(schema = @Schema(implementation = Fee.class))),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid") })
    @RequestMapping(value = "/fees/{feeId}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Fee> updateFeeById(@Parameter(in = ParameterIn.PATH, description = "The FeeId used to update the service information", required=true, schema=@Schema()) @PathVariable("feeId") Long feeId, @Parameter(in = ParameterIn.DEFAULT, description = "The Fee to update.", required=true, schema=@Schema()) @Valid @RequestBody FeeDto body);

}

