/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nms.apis;


import com.nms.models.Privilege;
import com.nms.models.PrivilegeDto;
import com.nms.models.ResponseModel;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-30T11:45:01.773Z[GMT]")
public interface PrivilegesApi {

    @Operation(summary = "add a new Privilege", description = "Adds add a new Privilege to the system", tags={ "Privilege Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Privilege created"),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid"),
        
        @ApiResponse(responseCode = "409", description = "an existing Privilege already exists") })
    @RequestMapping(value = "/privileges",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Privilege> addPrivilege(@Parameter(in = ParameterIn.DEFAULT, description = "Role to add", schema=@Schema()) @Valid @RequestBody PrivilegeDto body);


    @Operation(summary = "Delete a Privilege", description = "Delete Privilege", tags={ "Privilege Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Deleted."),
        
        @ApiResponse(responseCode = "400", description = "Unable to delete service.") })
    @RequestMapping(value = "/privileges/{privilegeId}",
        method = RequestMethod.DELETE)
    ResponseEntity<ResponseModel> deletePrivilegeById(@Parameter(in = ParameterIn.PATH, description = "The Privilege Id.", required=true, schema=@Schema()) @PathVariable("privilegeId") Long privilegeId);


    @Operation(summary = "searches for Privilege by name", description = "", tags={ "Privilege Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "search results matching criteria", content = @Content(schema = @Schema(implementation = Privilege.class))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/privileges/{privilegeName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Privilege> getPrivilegeByName(@Parameter(in = ParameterIn.PATH, description = "The roleName used to update the service information", required=true, schema=@Schema()) @PathVariable("privilegeName") String privilegeName);


    @Operation(summary = "get all priveleges", description = "", tags={ "Privilege Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Get all Privilege from database", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Privilege.class)))),
        
        @ApiResponse(responseCode = "400", description = "bad input parameter") })
    @RequestMapping(value = "/privileges",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Privilege>> getPrivileges();


    @Operation(summary = "update Privilege", description = "Update Privilege", tags={ "Privilege Management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Privilege updated.", content = @Content(schema = @Schema(implementation = Privilege.class))),
        
        @ApiResponse(responseCode = "400", description = "invalid input, object invalid") })
    @RequestMapping(value = "/privileges/{privilegeId}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Privilege> updatePrivilegeById(@Parameter(in = ParameterIn.PATH, description = "The PrivilegeId used to update the service information", required=true, schema=@Schema()) @PathVariable("privilegeId") Long privilegeId, @Parameter(in = ParameterIn.DEFAULT, description = "The Privilege to update.", required=true, schema=@Schema()) @Valid @RequestBody PrivilegeDto body);

}

