server:
  port: 9009

spring:
  application:
    name: AUTHENTICATION-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

    #MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/nms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    demographics-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    enabled: false

  jackson:
    serialization:
      fail-on-empty-beans: false


token:
  expiration_time: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739
  activation:
    url:
      path: /users/activate/**:password
  reset:
    token:
      expiration_time: 360000
email:
  verification:
    token:
      expiration_time: 864000000
authorization:
  token:
    header:
      prefix: Bearer
      name: Authorization
login:
  url:
    path: /users/login

signup:
  url:
    path: /users/signup

jsp:
  url:
    path: /**

password:
  reset:
    request:
      path: /password-reset-request
    path: /password-reset

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.glassfish.jersey: ERROR
    org.reflections: ERROR
    com.hcb.services.biorouter: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

