server:
  port: 0

spring:
  application:
    name: AUTHENTICATION-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

    #  #H2 Settings
    #  h2:
    #  console:
    #    enabled: true
    #    console:
    #      settings:
    #        web-allow-others: true
    #    path: /h2-console
    ##  datasource:
    ##    driver-class-name: org.h2.Driver
    ##    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    ##    password: sa
    ##    username: sa
    #H2 demographics as default
    #  datasource: {url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL, platform: h2,
    #               driver-class-name: org.h2.Driver, username: sa}
    #  jpa:
    #    hibernate: {ddl-auto: none}
    #    database-platform: {org.hibernate.dialect.H2Dialect}
    #    properties:
    #      hibernate: { show_sql: true, use_sql_comments: true, format_sql: true}
    #  h2:
    #    console:
    #      enabled: true
    #      path: /h2-console

    #MySQL
    datasource:
      url: mysql://localhost:3306/nms?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: password
    jpa:
      demographics-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update

      show-sql: true
      properties:
        hibernate:
          format_sql: true

  flyway:
    enabled: true

  jackson:
    serialization:
      fail-on-empty-beans: false


token:
  expiration_time: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739
  activation:
    url:
      path: /users/activate/**:password
  reset:
    token:
      expiration_time: 360000
email:
  verification:
    token:
      expiration_time: 864000000
authorization:
  token:
    header:
      prefix: Bearer
      name: Authorization
login:
  url:
    path: /users/login

signup:
  url:
    path: /users/signup

jsp:
  url:
    path: /**

password:
  reset:
    request:
      path: /password-reset-request
    path: /password-reset
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost


